= Release Notes Kafka Extension
:navtitle: Release notes

You can find the release notes for the Kafka Extension of version 4.10.0 and up, below.
For earlier releases, please go to the link:https://legacydocs.axoniq.io/reference-guide/release-notes/rn-extensions/rn-kafka[legacy documentation].

== Release 4.12.0

Upgrades the Kafka Extension to be compatible with Axon Framework 4.12.0, and updates various dependencies.

See the link:https://github.com/AxonFramework/extension-kafka/releases/tag/axon-kafka-4.12.0[GitHub release notes] for an exhaustive list of all changes.

== Release 4.11.1

=== _Enhancements_

- [#555] Add option to commit offsets link:https://github.com/AxonFramework/extension-kafka/pull/556[#556]
- Allow SubscribableKafkaMessageSource option of manually commiting offsets link:https://github.com/AxonFramework/extension-kafka/issues/555[#555]

=== _Contributors_

We'd like to thank all the contributors who worked on this release!

- link:https://github.com/bradskuse[@bradskuse]

== Release 4.11.0

=== _Features_

- KafkaPublisher Ack timeout can be set via properties and autoconfiguration link:https://github.com/AxonFramework/extension-kafka/pull/528[#528]

=== _Contributors_

We'd like to thank all the contributors who worked on this release!

- link:https://github.com/aupodogov[@aupodogov]

== Release 4.10.0

. Upgrades the Kafka Extension to be compatible with Axon Framework 4.10.0
. Updates various dependencies
. Adds the ability to ignore metadata keys

See the link:https://github.com/AxonFramework/extension-kafka/releases/tag/axon-kafka-4.10.0[GitHub release notes] for an exhaustive list of all changes.